---
deployment:
      tasks:
        - export DEPLOYPATH=/home/onezikoc/public_html/e-mpiya-foundation  # Add /<app_folder> if required
        - /bin/cp -r * $DEPLOYPATH                        #copy all recursively to $DEPLOYPATH
        
        